export const metadata = {
  title: 'เข้าสู่ระบบ',
  description: 'Generated by Next.js',
}

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <div>{children}</div>
  )
}
