version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API: https://courses-online-api.devsriwararak.com
      NEXT_PUBLIC_SECRET_KEY: 7vT2qrXQr3h6VRpF6eQhYv0q1P0aZQ5z8wL5O6Jt6gM=
      NEXT_PUBLIC_IMAGE_API: https://courses-online-api.devsriwararak.com
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start