import React from 'react'
import RegisterPage from '../../../components/auth/register'

export const metadata = {
  title: 'สมัครสมาชิก',
  description: 'Generated by Next.js',
}

const Loginpage = () => {
  return (
    <div>
        <RegisterPage/>
    </div>
  )
}

export default Loginpage