export const metadata = {
  title: 'เข้าสู่ระบบด้วย OTP',
  description: 'Generated by Next.js',
}

export default function LoginOtpLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>{children}</div>
  )
}
